[package]
<<<<<<< HEAD
name = "mkcd"
=======
name = "mkall"
authors = [ "Sawbez <sawbez@users.noreply.github.com>" ]
description = "A command that can create multiple paths at once."
>>>>>>> master
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
=======
clap = { version = "^4.1.1", features = ["derive"] }
exitcode = "^1.1.2"
>>>>>>> master
